const UsersData = [
    {
        "id": 1,
        "firstName": "Emily",
        "lastName": "Johnson",
        "maidenName": "Smith",
        "age": 28,
        "gender": "female",
        "email": "emily.johnson@x.dummyjson.com",
        "phone": "+81 965-431-3024",
        "username": "emilys",
        "password": "emilyspass",
        "birthDate": "1996-5-30",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVMdoYgPXTCToHRE7U3moSu9NtrSXIZDVQHhQTffKEHFfneCbnk1Gq9XKGiRHav8yf104&usqp=CAU",
        "bloodGroup": "O-",
        "height": 193.24,
        "weight": 63.16,
        "eyeColor": "Green",
      },
      {
        "id": 2,
        "firstName": "Michael",
        "lastName": "Williams",
        "maidenName": "",
        "age": 35,
        "gender": "male",
        "email": "michael.williams@x.dummyjson.com",
        "phone": "+49 258-627-6644",
        "username": "michaelw",
        "password": "michaelwpass",
        "birthDate": "1989-8-10",
        "image": "https://static.vecteezy.com/system/resources/thumbnails/004/607/806/small/man-face-emotive-icon-smiling-bearded-male-character-in-yellow-flat-illustration-isolated-on-white-happy-human-psychological-portrait-positive-emotions-user-avatar-for-app-web-design-vector.jpg",
        "bloodGroup": "B+",
        "height": 186.22,
        "weight": 76.32,
        "eyeColor": "Red",
      },
      {
        "id": 3,
        "firstName": "Sophia",
        "lastName": "Brown",
        "maidenName": "",
        "age": 42,
        "gender": "female",
        "email": "sophia.brown@x.dummyjson.com",
        "phone": "+81 210-652-2785",
        "username": "sophiab",
        "password": "sophiabpass",
        "birthDate": "1982-11-6",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDOdAlV5UEM-R_3Ijb9AJVrP-W9Q-pbXpeJzZi9UqFph663Hm6vcl3LvdkkuAWP4wMw-c&usqp=CAU",
        "bloodGroup": "O-",
        "height": 177.72,
        "weight": 52.6,
        "eyeColor": "Hazel",
      },
      {
        "id": 4,
        "firstName": "James",
        "lastName": "Davis",
        "maidenName": "",
        "age": 45,
        "gender": "male",
        "email": "james.davis@x.dummyjson.com",
        "phone": "+49 614-958-9364",
        "username": "jamesd",
        "password": "jamesdpass",
        "birthDate": "1979-5-4",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2N9Qhp0wemYgFz8BZFPnU6WAcbPw55P1c_Vrs41VVzZ9BQkSpGlthSNEVgpScXECKhrE&usqp=CAU",
        "bloodGroup": "AB+",
        "height": 193.31,
        "weight": 62.1,
        "eyeColor": "Amber",
      },
      {
        "id": 5,
        "firstName": "Emma",
        "lastName": "Miller",
        "maidenName": "Johnson",
        "age": 30,
        "gender": "female",
        "email": "emma.miller@x.dummyjson.com",
        "phone": "+91 759-776-1614",
        "username": "emmaj",
        "password": "emmajpass",
        "birthDate": "1994-6-13",
        "image": "https://img.freepik.com/premium-vector/professional-businesswoman-avatar-icon-flat-vector-isolated-white-background_1120563-20454.jpg",
        "bloodGroup": "AB-",
        "height": 192.8,
        "weight": 63.62,
        "eyeColor": "Green",
      },
      {
        "id": 6,
        "firstName": "Olivia",
        "lastName": "Wilson",
        "maidenName": "",
        "age": 22,
        "gender": "female",
        "email": "olivia.wilson@x.dummyjson.com",
        "phone": "+91 607-295-6448",
        "username": "oliviaw",
        "password": "oliviawpass",
        "birthDate": "2002-4-20",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOJBFfUZIEE_2pHywraXZ77hD1lQHLNfKnBGJ0XGf6Vo9r95FbACA_xxOi-nct6pXK7kM&usqp=CAU",
        "bloodGroup": "B+",
        "height": 182.61,
        "weight": 58,
        "eyeColor": "Hazel",
      },
      {
        "id": 7,
        "firstName": "Alexander",
        "lastName": "Jones",
        "maidenName": "",
        "age": 38,
        "gender": "male",
        "email": "alexander.jones@x.dummyjson.com",
        "phone": "+61 260-824-4986",
        "username": "alexanderj",
        "password": "alexanderjpass",
        "birthDate": "1986-10-20",
        "image": "https://static.vecteezy.com/system/resources/previews/004/476/164/non_2x/young-man-avatar-character-icon-free-vector.jpg",
        "bloodGroup": "AB-",
        "height": 153.89,
        "weight": 77.42,
        "eyeColor": "Blue",
      },
      {
        "id": 8,
        "firstName": "Ava",
        "lastName": "Taylor",
        "maidenName": "",
        "age": 27,
        "gender": "female",
        "email": "ava.taylor@x.dummyjson.com",
        "phone": "+1 458-853-7877",
        "username": "avat",
        "password": "avatpass",
        "birthDate": "1997-8-25",
        "image": "https://cbx-prod.b-cdn.net/COLOURBOX56424698.jpg?width=800&height=800&quality=70",
        "bloodGroup": "AB-",
        "height": 168.47,
        "weight": 57.08,
        "eyeColor": "Hazel",
      },
      {
        "id": 9,
        "firstName": "Ethan",
        "lastName": "Martinez",
        "maidenName": "",
        "age": 33,
        "gender": "male",
        "email": "ethan.martinez@x.dummyjson.com",
        "phone": "+92 933-608-5081",
        "username": "ethanm",
        "password": "ethanmpass",
        "birthDate": "1991-2-12",
        "image": "https://static.vecteezy.com/system/resources/previews/004/477/337/original/face-young-man-in-frame-circular-avatar-character-icon-free-vector.jpg",
        "bloodGroup": "AB+",
        "height": 159.19,
        "weight": 68.81,
        "eyeColor": "Hazel",
      },
      {
        "id": 10,
        "firstName": "Isabella",
        "lastName": "Anderson",
        "maidenName": "Davis",
        "age": 31,
        "gender": "female",
        "email": "isabella.anderson@x.dummyjson.com",
        "phone": "+49 770-658-4885",
        "username": "isabellad",
        "password": "isabelladpass",
        "birthDate": "1993-6-10",
        "image": "https://static.vecteezy.com/system/resources/thumbnails/004/899/680/small/beautiful-blonde-woman-with-makeup-avatar-for-a-beauty-salon-illustration-in-the-cartoon-style-vector.jpg",
        "bloodGroup": "A-",
        "height": 150.56,
        "weight": 50.1,
        "eyeColor": "Brown",
      },
]

export default UsersData ;